### ISSUE TITLE
As a developer, I need to port the Cache report to Drupal 8

### ISSUE THREAD

**Issue by fluxsauce** [fluxsauce/site_audit#15]
# Checks

These are the existing checks. Please use your best judgement in determining how to port to Drupal 8; it's very possible that some of these have changed.

For all items, verify that the recommendations are still valid and update the paths if needed.
## Anon

Already implemented.
## Backends
- [x] Check for equivalent of `cache_backends`
- [ ] If a string, fail (verify if valid for Drupal 8)
- [ ] If none, info
- [ ] If not empty, list
- [ ] Action - if info:
  - [ ] Pantheon - suggest redis
  - [ ] Acquia - suggest memcache
  - [ ] Else suggest both
- [ ] Action - if fail, describe what it should be (probably an array)
## Bins
- [x] List available cache bins, if any.
- [ ] Render as Text
- [ ] Render as HTML
- [ ] Render as JSON
## DefaultClass
- [ ] List cache_default_class
- [ ] If there are cache backends available but the default class is still the database, warn
## Lifetime
- [ ] Check the cache lifetime; if it's not set or infinite, pass
- [ ] If it is set, warn and describe how long it's set for
## Lock
- [ ] Detect if `lock_inc` is set
- [ ] If it's not, info
- [ ] If it is, pass
- [ ] Port vendor recommendations into action
## PageCompression
- [ ] Check if set
- [ ] If Pantheon and set, fail
- [ ] If Pantheon and unset, pass
- [ ] Else if set, pass
- [ ] If not set, fail
- [ ] Port vendor recommendations into action
## PageExpire
- [x] Check if set to at least 15 minutes
- [x] If development, report as info if unset
- [x] If not development, report as fail if unset
- [x] If it's greater than 15 minutes in seconds, pass
- [x] Otherwise warn
- [x] Provide action
## PreprocessCss
- [x] If set, pass
- [x] If dev, info
- [x] If not dev, fail
- [x] Provide action
## PreprocessJs
- [x] If set, pass
- [x] If dev, info
- [x] If not dev, fail
- [x] Provide action

**Comment by shivanshuag** [comment]
I don't think that [Lock API](https://api.drupal.org/api/drupal/core!lib!Drupal!Core!Lock!LockBackendInterface.php/group/lock/8) provdes alternate implementations in Drupal 8. 
PageCompression and Minimum Cache Lifetime setting is also not present in Durpal 8

**Comment by shivanshuag** [comment]
I don't understand why you check for cache backend to be a string.

**Comment by fluxsauce** [comment]
> I don't understand why you check for cache backend to be a string.

Because a string is incorrect, it should be an array, and people make mistakes in their configuration that I want to educate them about. This solves a particular problem I saw at Pantheon, people would say that they had enabled Redis but it wasn't because the config was wrong.

**Comment by shivanshuag** [comment]
Ok. I don't think this is necessary in Drupal 8. Configuration has changed in Drupal 8. See the Configuration section in https://api.drupal.org/api/drupal/core!modules!system!core.api.php/group/cache/8

**Comment by fluxsauce** [comment]
Yup, leftover from Drupal 7!

**Comment by shivanshuag** [comment]
Page Caching is also enabled by default(this was implemented recently), so I think PageInternal check is not needed now.
