### ISSUE TITLE
As a developer, I need to port the Block report to Drupal 8

### ISSUE THREAD

**Issue by fluxsauce** [fluxsauce/site_audit#16]
# Checks

These are the existing checks:
## Enabled
- [ ] Check if enabled
- [ ] If it doesn't, abort
- [ ] If it is, check if there is a default theme
  - [ ] If there is no default theme, warn
- [ ] Else pass
## Cache
- [ ] Check if block caching is enabled
- [ ] If it is, pass
- [ ] Determine if the node_grants check is still relevant, and if it is, set a warning
- [ ] If dev environment and block caching is off, info
- [ ] Else if block caching is off, fail
## CacheReport
- [ ] List all available blocks by module, info and state
- [ ] Ensure it renders in HTML
- [ ] Ensure it renders in text
- [ ] Ensure it renders in JSON

**Comment by shivanshuag** [comment]
In Drupal 8, blocks are cached by default ([all entities are](https://drupalwatchdog.com/volume-4/issue-1/automagic-speed-cache)) using a technique known as [render caching](https://www.acquia.com/blog/drupal-8-performance-render-caching) which is independent of node access restrictions. So, the Cache check is not needed. Even the Cache Report check is not needed

**Comment by fluxsauce** [comment]
As block caching is handled by entity caching, there's no need to explicitly check for this in Drupal 8. Therefore, this report is deprecated and implementation is not needed. Good job, thanks for the research!
