### ISSUE TITLE
As a developer, I need to port the Content report to Drupal 8

### ISSUE THREAD

**Issue by fluxsauce** [fluxsauce/site_audit#18]
# Checks

I'm making some fairly broad assumptions about Drupal 8 in that these basic concepts won't change. Instead of content types, do checks for content entity types.
## ContentTypes
- [ ] Rename to Content Entity Types.
- [x] List content entity types and counts for each
- [x] Render as Text
- [x] Render as HTML
- [x] Render as JSON
- [x] Save unused content type counts
- [x] Save entity counts
## ContentTypesUnused
- [ ] Rename to Content Entity Types Unused.
- [x] If there are no unused content entity types, pass
- [x] Else list unused content entity types
## DuplicateTitles
- [x] Scan all entities for duplicate titles
- [x] If found, warn
- [x] If none, pass
## Taxonomy Enabled

This is a new check.
- [x] Check if taxonomy module is enabled
- [x] If yes, Pass
- [x] If no, Info and abort
## Vocabularies
- [x] List count and names by vocabulary
- [x] Save unused
- [x] List Vocabularies and Term counts
  - [x] Render as Text
  - [x] Render as HTML
  - [x] Render as JSON
## VocabulariesUnused
- [x] If there are no unused vocabularies
- [x] Else list unused vocabularies
## FieldEnabled
- [x] Check if enabled
- [x] If not, info and abort
- [x] else pass
## FieldCount
- [x] Count number of distinct fields
- [x] If 0, fail and abort and give action
- [x] If more than 75, warn
- [x] List Name and Type
  - [x] Render as Text
  - [x] Render as HTML
  - [x] Render as JSON
## FieldInstances
- [x] Determine Drupal 8 equivalent of `field_info_field_map`
- [x] List Entity Type, Field Name, Bundle Name, and Count
  - [x] Render as Text
  - [x] Render as HTML
  - [x] Render as JSON
## FieldsUnused
- [x] If there are unused fields, warn and list unused fields
- [x] Else info

**Comment by shivanshuag** [comment]
I am unable to understand what Field Instances check is doing and how it is helpful.

**Comment by fluxsauce** [comment]
@shivanshuag one of the aspects of a Drupal site audit is determining what structures are being used and how. Therefore, exploring field usage across entities is important in identifying potentials for removal and/or optimization. If there are field instances that aren't used in any entity, then they can be completely removed. If they are used only in some entities, then they should be removed from where it's not necessary.

I'm using https://api.drupal.org/api/drupal/modules!field!field.info.inc/function/field_info_field_map/7 in the Drupal 7 version as a helper, but that's obviously not available in Drupal 8.

Does that help clarify?

**Comment by shivanshuag** [comment]
https://github.com/fluxsauce/site_audit/blob/7.x-1.x/Check/Content/FieldInstances.php#L109-L113
What is the use of fieldCondition without any operator on the value of the field? Which entities will this query fetch?

**Comment by shivanshuag** [comment]
never mind, got the answer.

**Comment by fluxsauce** [comment]
Are you on track to complete this by the 24th?
