### ISSUE TITLE
As a developer, I need to review the project's coding and submission standards

### ISSUE THREAD

**Issue by fluxsauce** [fluxsauce/site_audit#20]
Due to the time differences, it is extremely important to be clear in how we communicate. By defining these criteria ahead of time, communication and expectations can be clearly and cleanly managed. 

Please read this over fully and let me know if you have any questions or concerns. If you're good, just reply with a comment saying you've read it and close it. Thanks!
# Summary
- Don't commit directly, use logically named branches and pull requests
- All code must use Drupal coding standards and use the existing project structure
- Include instructions on how to test each pull request
- Address all feedback either with a commit or a reply
- Use the labels on PRs and issues to request help or to show that it's ready for review again
- You'll be fine and I'm sure your work will be awesome!
# Details
## Branches
- Do not commit directly on the 7.x or 8.x branches.
- All work should take place on a branch, one per issue.
- Branch parents should be the latest commit on the 7.x or 8.x branch
- Branches should be logically named with semantic context, like `cron-report`
- Commit your work often and push to GitHub.
- Branches should only be merged through pull requests.
- Branches should only be merged by the mentor and after passing functional and code review.
- Branches will be deleted post merge.
- Merge the parent branch in with the child if it's out-of-date.
## Coding standards
- All code should adhere to [Drupal coding standards](https://www.drupal.org/coding-standards)
- All code must pass PHP_CodeSniffer using the relevant sniffs for the major version of Drupal
- The directory structure should maintain the layout established in the 7.x version of site_audit
## Acceptance criteria

Each pull request should have the following:
- Link to the Issue
- Instructions for testing check and report, including how to pass and fail each test.
  - Drush instructions are preferred
  - The ability to copy and paste commands is optimal
  - Use [GitHub Flavored Markdown](https://help.github.com/articles/github-flavored-markdown/) for readability

For example:

---

Issue #14 - best practices
- [ ] Fast 404
  - [ ] Warn - use unaltered `settings.php`
  - [ ] Pass - uncomment `$config['system.performance']['fast_404']['exclude_paths']` `$config['system.performance']['fast_404']['paths']` and `$config['system.performance']['fast_404']['html']` in `settings.php`

---

And so forth. I've written each issue include specific criteria which should map pretty closely to the way the Drupal 7 versions of the checks work, and those can be used as a starting place.

In addition, the code must pass PHP_CodeSniffer.
## Reviewing

As I review each pull request, I'll give feedback either inline on the code, or respond to the issue itself. Please take time to address each piece of feedback, either by changing the code in question or by replying to the comment. You don't have to do both; if the code change resolve the concern, no reply is needed.
## Labels

I've set up labels for issues and pull requests: https://github.com/fluxsauce/site_audit/labels
- _help_ - Please use this on an issue or PR if need help with something or aren't sure how to proceed.
- _needs work_ - I'll apply this if there's a problem or a question that is preventing me from merging your changes. Feel free to remove the label when you've addressed the concerns.
- _passes code review_ - I'll apply this if a PR passes code review; please do not apply this label yourself.
- _passes functional review_ - I'll apply this if a PR passes functional review; please do not apply this label yourself.
- _priority_ - Apply this if something is very important.

If a story has both _passes code review_ and _passes functional review_, then it's ready to be merged.

**Comment by shivanshuag** [comment]
I have read this. Thanks.

**Comment by fluxsauce** [comment]
No questions or concerns? It's okay to question it :-) If you're not comfortable with anything or think something should change, please let me know.

**Comment by shivanshuag** [comment]
I think there should be one branch per check, not per issue. This will allow having one pull request per check, which can be tested and merged independent of the other checks in the same issue.

**Comment by fluxsauce** [comment]
Okay, we can try that. I have a minor concern about dependencies when you have a PR that requires another PR to be merged, but we'll deal with it if it happens.

**Comment by fluxsauce** [comment]
While I'm thinking of it, please also add the appropriate milestone and assign the PRs to me. I took care of it for the existing.

**Comment by fluxsauce** [comment]
Moving this to https://github.com/fluxsauce/site_audit/wiki
