### ISSUE TITLE
As a student, I need to provide actionable items based on professional interviews

### ISSUE THREAD

**Issue by fluxsauce** [fluxsauce/site_audit#25]
Based on the four interviews - #13, #12, #9 and #8 - provide a summary of ways that site_audit can be extended to meet the needs of professionals who audit Drupal sites. In particular:
- What Reports and/or Checks should be added? Describe why it's needed, what should be checked, how it should be checked, and what the results should look like.
- What third-party tools could site_audit be integrated with? Provide specific links directly to Drupal.org project page and/or official site.
- What other features can site_audit provide that would be helpful to others?

Please reply to this issue with the answers to these questions.

**Comment by fluxsauce** [comment]
@shivanshuag status update?

**Comment by shivanshuag** [comment]
## New Checks

Checking the environment on which the web site is hosted is an important part of an audit as it directly affects the performance and security of the site. If the platform is not good enough, the auditor can recommend the client to move to a better platform.

Following three things can be checked by running `php -i` on the site environment
- Php Version - Checks the php version being used.
- Php Memory - Checks the maximum memory available to php.
- OpcodeCache - Check if APC is enabled for php and its version.

If the website is public, using the url and doing a curl request can give us
- Web server  - check the webserver being used to serve the site.

If the site uses MySql, 
- MySql version - Can be done by running `SHOW VARIABLES LIKE "%version%` sql query.
- Drush - check the verison of drush being used. Can be done by running `drush version` command.

## Executive Summary

Site audit can provide an executive summary of the audit. This can be implemented in the following manner 
- For each check the score can be used to include a line or two regarding that aspect of the Drupal site in the summary. 
- The summary should be such that a layman can understand it.

## Third Party tools integration

### [Webpagetest](http://www.webpagetest.org)

Tests the performance of a drupal website. An issue for integrating this in to site_audit already exists [here](https://www.drupal.org/node/2486845). Webpagetest provide REST API's which can be easily used from site_audit using cURL. To use the API's, a key is needed which one can get by following the instructions given [here](http://www.webpagetest.org/getkey.php) 

### [Pareview](http://pareview.sh/pareview/httpgitdrupalorgsandboxjpstrikesback1844058git)

To review the custom code in a Drupal site. Pareview is a bash script which performs the following checks on a drupal project
- [Drupal  Coder](http://drupal.org/project/coder) sniffs
- [DrupalSecure](https://www.drupal.org/sandbox/coltrane/1921926) sniffs
- Runs [codespell](https://www.drupal.org/sandbox/coltrane/1921926) to check code for common misspellings 
- Runs [ESLint](http://eslint.org/) to check for [Drupal js coding standards](https://www.drupal.org/node/172169)
- Check if `README.txt` or `README.md` is present and is unique.
- Checks for `LICENSE.txt` and recommends to remove it
- Checks if `translations folder is present and recommends to remove it
- Checks for `.DS_Store .idea node_modules .project .sass-cache .settings vendor` files and recommends to remove them
- Checks for backup files (`*~`) and recommends to remove them
- Checks for `version`, `project` and `datestamp` in `.info.yml` file and recommends to remove them if present
- Checks for php delimiter at the end of php files and discourages from using it
- Checks for function names without module prefix in the code and recommends against it
- Checks for bad line endings in files
- Checks for  old CVS $Id$ tag and recommends to remove them
- Checks for PHP parse errors
- Checks for  \feff character check at the beginning of files and discourages from using it
- Checks if the project contains automated tests and recommends to write tests if none found

These tests can be included in site_audit.

### [Security Review](https://www.drupal.org/project/security_review)

Not sure if it makes sense integrating it with site_audit or keep it separate. Including it into site_audit certainly makes the audit report more complete. There are pending issues for integrating security review into site_audit in both - [the site_audit drupal project](https://www.drupal.org/node/2129415) and the [security review drupal project](https://www.drupal.org/node/2279283).
Security Review is a drupal module with drush support, so it has to be present in the site codebase for it to run. It exposes API's documented [here](cgit.drupalcode.org/security_review/tree/API.txt?id=refs/heads;id2=7.x-1.x) which can be used by other modules to run it's checks. There is an already a patch for integration in security review issue queue which works but needs more refinement. There is still no Drupal 8 release of the module, but Security Review is also a GSoC'15 project, so I am hoping for Drupal 8 release soon.

**Comment by fluxsauce** [comment]
Hi @shivanshuag , good work so far! Can you please review https://www.drupal.org/project/issues/site_audit?categories=All and include links to existing issues that resolve the identified issues?

The Third Party tools integration section needs work; please detail how site_site audit should integrate with each service or tool. For example, WebPageTest.org has an API, and Security Review is a Drupal module with drush support and an outstanding feature request to integrate with site_audit.

**Comment by fluxsauce** [comment]
@shivanshuag the actual `PAReview.sh` project pages are http://pareview.sh/ and https://github.com/klausi/pareviewsh - they list specific tools that are used, the script just runs them. Some of them are new to the site_audit, others are existing. List each component and how site_audit can integrate with them, and this should be good to go!

**Comment by fluxsauce** [comment]
@shivanshuag any progress? I haven't heard back from you about the last piece about PAReview?

**Comment by fluxsauce** [comment]
Thank you! Marking this as resolved.
