### ISSUE TITLE
As a developer, I need to port the Extensions report to Drupal 8

### ISSUE THREAD

**Issue by fluxsauce** [fluxsauce/site_audit#28]
# Checks

Given how modules are added and removed from Drupal 8, I'm curious how things like the missing, duplicate and disabled checks will work out.
## Count
- [x] As info, list the number of enabled modules
- [x] If there are more than 150, warn and give actionable recommendation to disable and remove
## Dev
- [x] Update list of modules to only include modules with Drupal 8 versions
- [x] See what admin_menu is doing for its list of development modules and update that list as well
- [x] List modules by name, reason if found
- [x] If found but dev, INFO
- [x] If found, WARN
- [x] If none found, PASS
## Disabled

This one might be different in Drupal 8; use your best judgement.
- [ ] List disabled but not uninstalled modules
- [ ] If found, WARN
- [ ] If none, PASS
## Duplicate

I'm assuming this is possible, but not sure. Test first and let me know if it isn't possible!
- [x] Search for duplicate extensions
- [x] Whitelist safe duplicates (tests)
- [x] Allow paths within installation profiles
- [x] NEW FEATURE - allow versions that are greater than what's in an installation profile if that version is enabled
- [x] If duplicates are found, warn
- [x] Else pass
## Missing

Not sure what Drupal 8 will do if you remove the code for a module but leave it installed / enabled. I know it's performance problems in Drupal 7.
- [ ] Fail if any are enabled but the file doesn't exist
- [ ] Else pass
- [ ] Describe action to fix
## Unrecommended
- [x] Remove APC from unrecommended list
- [x] Remove nodesquirrel from Pantheon unrecommended list
- [x] Add fast_404 to Pantheon only list and remove from general list
- [x] Remove any modules without a Drupal 8 version
- [x] Check for unrecommended modules that are in codebase (not just installed)
- [x] If found, FAIL
- [x] Else PASS
## Version

Do not include this, I'm going to be dropping it from Drupal 7.

**Comment by shivanshuag** [comment]
- Drupal 8 has no concept of disabled modules. They are either enabled or uninstalled, so `Disabled` check is not needed.
- If any module is missing, Drupal 8 and Drush throw an error while bootstrapping. So, I am not sure whether `Missing` check is needed.

**Comment by shivanshuag** [comment]
> NEW FEATURE - allow versions that are greater than what's in an installation profile if that version is enabled

This check is not clear to me. Please explain what is to be done and how this helps. Thanks

**Comment by fluxsauce** [comment]
> This check is not clear to me. Please explain what is to be done and how this helps. Thanks

In the future, please don't submit a pull request if there are outstanding questions. Also, the "help!" label is helpful as well :-)

Installation profile has `rules 8.x-3.0-unstable3`, user has downloaded and enabled `rules 8.x-3.0-unstable4` because the installation profile is out-of-date.
