### ISSUE TITLE
As a developer, I need to implement the Security report in Drupal 8

### ISSUE THREAD

**Issue by fluxsauce** [fluxsauce/site_audit#39]
This one is going to need investigation and may not be necessary. Or it might, I don't know!

There's currently one check, and that check should persist if it can. It'll also be the place where `security_review` can implement their own check(s).

The Drupal 7 version checked the menu_router table for malicious callbacks, where malicious is interpreted as anything that can run arbitrary code.

Your mission:
- Assume you have complete control over the codebase
- Assume you have complete control over the database
- See if it's possible to create a Drupal 8 menu item and or routing callback to phpinfo
- If so, adapt the existing check for that and all the other potential callbacks
- If not, describe why it's not possible
- Either way, describe what you tried

**Comment by fluxsauce** [comment]
Hi @shivanshuag , how's it going on this one?

**Comment by shivanshuag** [comment]
I am still stuck with the Google Page speed insights check. Some functions which that test uses have been removed in drupal 8 and the replacements don't work with drush. Can't figure out if it is a bug in drush or my code. Hopefully, I will finish both the issues by today.
