### ISSUE TITLE
As a developer, I need to set up a local development environment

### ISSUE THREAD

**Issue by fluxsauce** [fluxsauce/site_audit#4]
Requirements:
- [x] PHP 5.5
  - [x] opcache (enabled)
  - [x] <s>APC (installed, but not enabled)</s>
  - [x] xdebug (enabled, but not profiling automatically)
- [x] MySQL 5.6 OR MariaDB 10.0
  - [x] UTF-8 database for Drupal 7
  - [x] UTF-8 database for Drupal 8
- [x] Apache OR ngxinx
- [x] Composer - https://getcomposer.org/
- [x] Drush 7, installed via Composer - http://www.drush.org/
- [x] PHP IDE - your choice, but must be an actual IDE with PHP support (not just syntax highlighting). If unsure, consider NetBeans for PHP or Eclipse for PHP.
- [x] PHP_CodeSniffer - install two versions
  - [x] 1.5.6 for Drupal 7
  - [x] 2.3.2 for Drupal 8
- [x] Redis server and https://github.com/phpredis/phpredis
- [x] Memcache
- [x] A program to screen capture to animated gifs - if I recall, you're using Linux, so http://askubuntu.com/questions/107726/how-to-create-animated-gif-images-of-a-screencast

As an option, consider using something like https://box.scotch.io/ to save time.

**Comment by fluxsauce** [comment]
Hi @shivanshuag, how's it going?

**Comment by shivanshuag** [comment]
APC is not compatible with PHP 5.5, so I am unable to install it. What is it needed for?

**Comment by shivanshuag** [comment]
Redis has two clients for PHP - Predis and PhpRedis. Which one should I install?

**Comment by shivanshuag** [comment]
Is there a way to install both versions of PHP_CodeSniffer on the same machine? I tried using composer to install codesniffer but composer doesn't have this feature.

**Comment by fluxsauce** [comment]
> APC is not compatible with PHP 5.5

You're correct! I honestly forgot, it made sense with PHP 5.4 but not with 5.5. The purpose was to facilitate https://www.drupal.org/node/2360389

**Comment by fluxsauce** [comment]
> Redis has two clients for PHP - Predis and PhpRedis. Which one should I install?

https://github.com/phpredis/phpredis is more common and is used by Pantheon, I recommend that one.

**Comment by fluxsauce** [comment]
> Is there a way to install both versions of PHP_CodeSniffer on the same machine?

Install the newer version with Composer. For the older version for use with Drupal 7:

```
git clone git://github.com/squizlabs/PHP_CodeSniffer.git
cd PHP_CodeSniffer
git checkout 1.5.6
```

Then you should be able to use the instructions at https://www.drupal.org/node/1419988

**Comment by shivanshuag** [comment]
Why do we need two different versions of PHP_CodeSniffer for Drupal 7 and  Drupal 8? I tried PHP_CodeSniffer 2.3.2 with a drupal 7 module and it worked.

**Comment by fluxsauce** [comment]
> I tried PHP_CodeSniffer 2.3.2 with a drupal 7 module and it worked.

You didn't follow the instructions at https://www.drupal.org/node/1419988

Coder for Drupal 8 requires greater than 2, Coder for Drupal 7 requires less than 2.

```
./vendor/bin/phpcs --standard=sites/all/modules/contrib/coder/coder_sniffer/Drupal --extensions=php,module,inc,install,test,profile,theme sites/all/modules/custom/badcamp_placeholder
PHP Fatal error:  Uncaught exception 'PHP_CodeSniffer_Exception' with message 'Class PHP_CodeSniffer_CommentParser_ClassCommentParser not found' in /Users/jon/projects/badcamp-2015/sites/all/modules/contrib/coder/coder_sniffer/Drupal/Sniffs/Commenting/FileCommentSniff.php:13
Stack trace:
#0 /Users/jon/projects/badcamp-2015/vendor/squizlabs/php_codesniffer/CodeSniffer.php(1318): include_once()
#1 /Users/jon/projects/badcamp-2015/vendor/squizlabs/php_codesniffer/CodeSniffer.php(560): PHP_CodeSniffer->registerSniffs(Array, Array)
#2 /Users/jon/projects/badcamp-2015/vendor/squizlabs/php_codesniffer/CodeSniffer/CLI.php(830): PHP_CodeSniffer->initStandard(Array, Array)
#3 /Users/jon/projects/badcamp-2015/vendor/squizlabs/php_codesniffer/CodeSniffer/CLI.php(95): PHP_CodeSniffer_CLI->process()
#4 /Users/jon/projects/badcamp-2015/vendor/squizlabs/php_codesniffer/scripts/phpcs(25): PHP_CodeSniffer_CLI->runphpcs()
#5 {main}
  thrown in /Users/jon/projects/badcamp-2015/sites/all/modules/contrib/coder/coder_sniffer/Drupal/Sniffs/Commenting/FileCommentSniff.php on line 13

Fatal error: Uncaught exception 'PHP_CodeSniffer_Exception' with message 'Class PHP_CodeSniffer_CommentParser_ClassCommentParser not found' in /Users/jon/projects/badcamp-2015/sites/all/modules/contrib/coder/coder_sniffer/Drupal/Sniffs/Commenting/FileCommentSniff.php:13
Stack trace:
#0 /Users/jon/projects/badcamp-2015/vendor/squizlabs/php_codesniffer/CodeSniffer.php(1318): include_once()
#1 /Users/jon/projects/badcamp-2015/vendor/squizlabs/php_codesniffer/CodeSniffer.php(560): PHP_CodeSniffer->registerSniffs(Array, Array)
#2 /Users/jon/projects/badcamp-2015/vendor/squizlabs/php_codesniffer/CodeSniffer/CLI.php(830): PHP_CodeSniffer->initStandard(Array, Array)
#3 /Users/jon/projects/badcamp-2015/vendor/squizlabs/php_codesniffer/CodeSniffer/CLI.php(95): PHP_CodeSniffer_CLI->process()
#4 /Users/jon/projects/badcamp-2015/vendor/squizlabs/php_codesniffer/scripts/phpcs(25): PHP_CodeSniffer_CLI->runphpcs()
#5 {main}
  thrown in /Users/jon/projects/badcamp-2015/sites/all/modules/contrib/coder/coder_sniffer/Drupal/Sniffs/Commenting/FileCommentSniff.php on line 13
jon@Decker ~/projects/badcamp-2015 (master) $ ./vendor/bin/phpcs --version
PHP_CodeSniffer version 2.3.2 (stable) by Squiz (http://www.squiz.net)
```

vs

```
jon@Decker ~/projects/badcamp-2015 (master) $ ~/.composer/vendor/bin/phpcs --standard=sites/all/modules/contrib/coder/coder_sniffer/Drupal --extensions=php,module,inc,install,test,profile,theme sites/all/modules/custom/badcamp_placeholder

FILE: ...sites/all/modules/custom/badcamp_placeholder/badcamp_placeholder.module
--------------------------------------------------------------------------------
FOUND 5 ERROR(S) AFFECTING 5 LINE(S)
--------------------------------------------------------------------------------
  3 | ERROR | The second line in the file doc comment must be " * @file"
  4 | ERROR | The third line in the file doc comment must contain a description
    |       | and must not be indented
 22 | ERROR | Missing function doc comment
 28 | ERROR | Missing function doc comment
 35 | ERROR | Files must end in a single new line character
--------------------------------------------------------------------------------
UPGRADE TO PHP_CODESNIFFER 2.0 TO FIX ERRORS AUTOMATICALLY
--------------------------------------------------------------------------------


FILE: ...ites/all/modules/custom/badcamp_placeholder/badcamp_placeholder.tpl.php
--------------------------------------------------------------------------------
FOUND 1 ERROR(S) AND 1 WARNING(S) AFFECTING 2 LINE(S)
--------------------------------------------------------------------------------
  1 | WARNING | No PHP code was found in this file and short open tags are not
    |         | allowed by this install of PHP. This file may be using short
    |         | open tags but PHP does not allow them.
 12 | ERROR   | Files must end in a single new line character
--------------------------------------------------------------------------------
UPGRADE TO PHP_CODESNIFFER 2.0 TO FIX ERRORS AUTOMATICALLY
--------------------------------------------------------------------------------

jon@Decker ~/projects/badcamp-2015 (master) $ ~/.composer/vendor/bin/phpcs --version
PHP_CodeSniffer version 1.5.6 (stable) by Squiz (http://www.squiz.net)
```

Please read the instructions carefully and test.

**Comment by fluxsauce** [comment]
Hi @shivanshuag, how is it going with the multiple version of PHP_CodeSniffer and Drupal?

**Comment by fluxsauce** [comment]
Please complete this work and provide proof of the two versions of PHP_CodeSniffer working by checking a Drupal 7 and Drupal 8 module - use https://www.drupal.org/project/securesite as an example. Put the output into gists and place the links in this ticket; once I've got those, I'll close it.

Can you please get this done before you start working on development? Thanks!

**Comment by shivanshuag** [comment]
Took me some time to figure out that there is no problem with my installtion after all.
I am using different versions of Coder for different versions of CodeSniffer, so it works. I have prepared the gist - https://gist.github.com/shivanshuag/9c87118e8791f6bac86a

**Comment by fluxsauce** [comment]
Excellent, that's exactly what we need to get started! Thank you, closing.
