### ISSUE TITLE
Write Unit tests

### ISSUE THREAD

**Issue by shivanshuag** [fluxsauce/site_audit#42]
Issue #40 
Write tests which test for following functionality in each Check
### Fast404
- [x] Enable fast404 and make fast404 paths empty. Should Warn
- [x] Enable fast404 and add some paths to it. Should pass
- [x] Disable fast404. Should Warn
### Sites
- [ ] Create `sites/sites.php` as a symlink. Should Warn
- [ ] Ensure no `sites/sites.php`. Should Pass
### Multisite
- [ ] Create `sites/sites.php` but no directory for any site. Should Warn
- [ ] Ensure no `sites/sites.php` but some directories for multisite. Should Warn
### Settings
- [ ] Delete `/sites/default/settings.php`. Should Fail
- [ ] Make `/sites/default/settings.php` a symlink. Should Warn
### Services
- [ ] Delete `/sites/default/services.yml`. Should Fail
- [ ] Make `/sites/default/services.yml` a symlink. Should Warn
### SitesDefault
- [ ] Delete `/sites/default` directory. Should Fail
- [ ] Make `/sites/default` a symlink. Should Warn
### SitesSuperfluous
- [ ] Make a random directory inside `sites/default`. Should Warn
### PageExpire
- [x] Set `cache.page.max_age` to 0. Should Fail
- [x] Set `cache.page.max_age` between 0 and 900. Should Warn
### PreprocessCss
- [x] Set `css.preprocess` to false. Should Fail
### PreprocessJs
- [x] Set `js.preprocess` to false. Should Fail
### Usedbackend
- [x] This check depends on support provided by the platform that the test runs on. I am not sure how to test this. Need feedback.
## Codebase

All the checks in this report only provide some kind on info. Therefore, no tests required for this report.
### ContentEntityTypesUnused
- [x] Create a content entity type which is unused. Should Warn and list them
### DuplicateTitles
- [x] Create two nodes with same title. Should warn and list them
### VocabulariesUnused
- [x] Create a new vocabulary, but no terms in it. Should Warn and list the vocabulary
### Enabled
- [x] Run the cron. Should Pass
- [x] Set `threshold.autorun` to 0. Should Fail
- [x] Set `threshold.autorun` to  and run the cron. Should  Pass
- [x] Set `threshold.autorun` to  > 24 hours. Should Warn
- [ ] Put some spurious value in `threshold.autorun`. Should Fail
## Database

Platform Dependent.
### Dev
- [x]  Should Pass on defaut installation
- [x] Enable a dev module. Should Warn
### Unrecommended
- [x] Should pass on default installation
- [x]  Enable an unrecommended module. Should Warn
### Duplicate
- [x]  Put same extension in two paths. Should Warn
- [x] Check for the current installation profile. Make a directory `profiles/[installed profile]/modules` and put a module inside it. Put the same module inside `modules` directory but increase the version number. Install the module. Should Pass
- [x] Follow the instructions above, but don't install the module. Should Warn
- [x] Put the module with lower version number inside `modules` directory. Should Warn
### BlockedNumberOne
- [x] Block the user with uid 1. Should Fail
### WhoIsNumberOne
- [x] Delete user with uid 1. Should Fail
### 404
- [x]  Enable syslog and dblog. Make more than 10 requests to non existent urls. Should Warn
### Php
- [x] Create more than 10% php errors. Should Warn
### CacheOutput
- [ ] Enable views module. Set views caching to None. Should Fail or Warn
- [ ] Enable views module. Set to Tag caching. Should pass
- [ ] Set output caching to time with lifespan 0. Should warn or fail
### CacheResult
- [ ] Set result caching to time with lifespan 0. Should warn or fail
## Status

No unit test
## FrontEnd

No unit tests
### MenuRouter
- [x] Enable a module with malicious menurouter callback. Should Fail

**Comment by shivanshuag** [comment]
@fluxsauce I have started writing issue for Unit tests. Some of these seem too trivial. Please take a look and give feedback.

**Comment by shivanshuag** [comment]
The drupal-sandbox set up by the drush for testing uses multisite functionality. So, we cannot test multisite checks.

**Comment by shivanshuag** [comment]
@fluxsauce None of the Settings, Services, Sites and Multisites checks can be tested because durpal-sandbox set up by drush for testing uses the multisite functionality and these checks check for the relevant files in the `default` directory. I think we will have to fix these checks to work with multisite.

SitesSuperfluous check also doesn't exculde the multisite directories. This too will have to change.

I also found a bug in the Cron Enabled check. When the `threshold.autorun` is set to 0 and Cron has run in last 24 hours, it Passes. I think it should warn in the case. Is that the correct functionality?

**Comment by fluxsauce** [comment]
For the record, @shivanshuag wrote a great blog post on this subject - http://ninjaducks.in/hacking/writing-tests-for-drush-commands/

**Comment by fluxsauce** [comment]
> I also found a bug in the Cron Enabled check. When the threshold.autorun is set to 0 and Cron has run in last 24 hours, it Passes. I think it should warn in the case. Is that the correct functionality?

As a follow-up our discussion, that's a feature, not a bug; the use case is alternative cron runners, such as a combination of cron and drush, that don't use Drupal's built-in cron timing. As long as it runs every 24 hours, that's good.
