### ISSUE TITLE
Implement Static Code Analysis Report

### ISSUE THREAD

**Issue by shivanshuag** [fluxsauce/site_audit#45]
Issue #40
- [x] Decide whether to package the dependencies with site_audit or have the user install them separately
- [x] Decide on a way for the user to specify custom code
### PhpMessDetection
- [x] Discuss with mentor and determine the best strategy for integrating this tool with site_audit
- [x] Decide which [PHPMD Rules](http://phpmd.org/rules/index.html) should be included in this check. Some of them seem to be too strict.
- [x] Check wheher PHPMD is installed before running the check.
- [x] Determine a policy to assign score to this test and thresholds for passing and warning
- [x] Implement this check
### PhpCopyPasteDetection
- [x] Discuss with mentor and determine the best strategy to integrate this to site_audit
- [x] Decide on policy to assign score and thresholds for passing and warning.
- [x] Implement the check
### PhpDeadCodeDetection

This should be integrated in a way similar to PHPCPD.
- [x] Info - `--log-xml` option not present in phpdcd tool.
- [x] Pass - No dead code
- [x] Warn - If some dead code is present
### PhpLOC
- [x] Info - Display phploc info
### PhpCodeSniffer
- [x] Pass - No codesniffer violation
- [x] Warn - Atleast one condesniffer violation

**Comment by fluxsauce** [comment]
>  Decide whether to package the dependencies with site_audit or have the user install them separately

Install separately, add to `require-dev` in `composer.json`?

Regarding rule sets, take a look at https://github.com/atouchard/drupal-continuous-integration/tree/master/build - that looks like a potential starting place.

**Comment by shivanshuag** [comment]
phpdcd does not have an option to give the report in xml. There is a pr for this https://github.com/sebastianbergmann/phpdcd/pull/58 . Should I wait for the pr to be merged?
