### ISSUE TITLE
As a developer, I need to configure my local development environment

### ISSUE THREAD

**Issue by fluxsauce** [fluxsauce/site_audit#5]
Requirements:
- [x] Drupal 7.36 downloaded and installed via Drush
  - [x] Include Views and dependencies, Coder
  - [x] Bonus: Use Drush make to build site
- [x] Drupal 8.0.0-beta10 downloaded and installed via Drush
  - [x] Bonus: Use Drush make to build site
  - [x] Include Coder
- [x] Set up drush aliases for each site
  - [x] Know how to list all enabled modules for both Drupal 7 and 8
  - [x] Know how to install modules on both Drupal 7 and 8
- [x] Backup site database using drush, then restore
- [x] Check coding standards of a module using Coder / PHP_CodeSniffer on both Drupal 8 and Drupal 7

**Comment by shivanshuag** [comment]
I think we should use Drupal 8.0.0-beta10 instead of beta9. Beta 10 was released on April 29.

**Comment by fluxsauce** [comment]
> I think we should use Drupal 8.0.0-beta10 instead of beta9.

Agree. This issue was created before Beta 10 was released :-) I've updated the item.

**Comment by fluxsauce** [comment]
Hi @shivanshuag, do you consider this complete? If so, please close and comment. Thanks!

**Comment by shivanshuag** [comment]
Yes, this is complete. I have prepared some documentation for all the steps. I will link it and close the issue soon.

**Comment by shivanshuag** [comment]
Notes on this task are at - https://github.com/shivanshuag/site_audit/wiki/Configuring-local-development-environment

**Comment by fluxsauce** [comment]
Excellent! Good documentation, too. Thank you!
