### ISSUE TITLE
License for site_audit

### ISSUE THREAD

**Issue by shivanshuag** [fluxsauce/site_audit#68]
I think it would be great if site_audit has a license.

**Comment by fluxsauce** [comment]
Hey man, good to hear from you! It's GPLv2 - requirement for being on Drupal.org, but it's not reflected here yet. Will get that in here, good catch!

**Comment by fluxsauce** [comment]
Added to 8.x branch, thanks!

**Comment by shivanshuag** [comment]
Thanks!
