### ISSUE TITLE
Packagist information out of date

### ISSUE THREAD

**Issue by socketwench** [fluxsauce/site_audit#74]
Right now site_audit 8.x-2.x doesn't seem to install correctly. The underlying problem was that the Composer `type` was set to `drupal-module` and not `drupal-drush`. This was fixed in the repos, but Packagist doesn't seem to be updating. The last time 8.x-2.x was refreshed was 2/25, and the last type fix was on 3/9, so something's up.

I would fix it myself, but I don't have ownership over the packages on Packagist.

**Comment by socketwench** [comment]
It also appears that the site audit package there was manually created. It's not listed as a Virtual Package like other Drupal modules (see drupal/flag).

**Comment by socketwench** [comment]
Can you take a look at the Packagist entry, @fluxsauce? My username there is the same here.

**Comment by fluxsauce** [comment]
Some direct discussions took place via email involving Packagist support.

In short, I'm removing it from Packagist (it was added before Drupal supported it). When complete, I'll mark this as closed.
