### ISSUE TITLE
As a student, I should interview Four Kitchens about auditing sites

### ISSUE THREAD

**Issue by fluxsauce** [fluxsauce/site_audit#9]
Google Doc for notes: https://docs.google.com/document/d/1oLS2E5gssyJ4-tuP7ysUIS0hsSJjfhlZSdI-5j7LhH8/edit#heading=h.72mlvxlu8i8r

Interview goals:
- [x] Learn how professional services are performed
- [x] Learn how different professionals accomplish similar tasks
- [x] Identify "pain" points and areas of potential improvement
- [x] Document and plan Site Audit additions to address issues identified

Post-interview:
- [x] Summary - Please write a paragraph or two about what you learned. What was interesting? What surprised you?
- [x] Site Audit Action items - How can Site Audit be improved to address needs identified?

**Comment by fluxsauce** [comment]
Hi @shivanshuag , when is this interview scheduled?

**Comment by shivanshuag** [comment]
It is on 18th May, 10:00 AM Pacific Time

**Comment by fluxsauce** [comment]
Cool, thanks!
